# Generated by Django 5.2.6 on 2025-10-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_category_video_created_at_video_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('drama', 'Drama'), ('romance', 'Romance')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='media/videos/'),
        ),
    ]
