# Generated by Django 5.2.6 on 2025-10-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_category_video_created_at_video_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('romance', 'Romance'), ('drama', 'Drama')], max_length=55),
        ),
    ]
