# Generated by Django 5.2.6 on 2025-10-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_remove_video_thumbnail_url_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('drama', 'Drama'), ('romance', 'Romance')], max_length=55, null=True),
        ),
    ]
