# Generated by Django 5.2.6 on 2025-10-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('romance', 'Romance'), ('drama', 'Drama')], max_length=55, null=True),
        ),
    ]
