# Generated by Django 5.2.6 on 2025-10-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('drama', 'Drama'), ('romance', 'Romance')], max_length=55, null=True),
        ),
    ]
