# Generated by Django 5.2.6 on 2025-10-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_alter_video_category_alter_video_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('romance', 'Romance'), ('drama', 'Drama')], max_length=55),
        ),
    ]
