# Generated by Django 5.2.6 on 2025-10-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('romance', 'Romance'), ('drama', 'Drama')], max_length=55),
        ),
    ]
