# Generated by Django 5.2.6 on 2025-10-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_alter_video_video_file'),
        ('content', '0038_alter_video_category'),
    ]

    operations = [
    ]
