# Generated by Django 5.2.6 on 2025-10-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_merge_20251024_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('drama', 'Drama'), ('romance', 'Romance')], max_length=55),
        ),
    ]
